ecomapp/urls.py
from django.urls import path
from .views import *
app_name='ecomapp'
urlpatterns=[
    path('',HomeView.as_view(),name='home'),
     path('about/',AboutView.as_view(),name='about'),
     path('contact-us/',ContactView.as_view(),name='contact'),
     path('all-products/',AllProducts.as_view(),name='allproducts'),
     path('product/<slug:slug>/',ProductDetailView.as_view(),name='productdetail'),
     path('add-to-cart/<int:pro_id>/',AddToCartView.as_view(),name='addtocart'),
     path('my-cart/',AddMyCartView.as_view(),name='mycart'),
     path('manage-cart/<int:cp_id>/',ManageCartView.as_view(),name='managecart'),
     path('empty-cart/',EmptyCartView.as_view(),name='emptycart'),
     path('checkout/',CheckoutView.as_view(),name='checkout'),

     path('esewarequest/',EsewaRequestView.as_view(),name='esewarequest'),
     path('esewa-verify/',EsewaVerifyView.as_view(),name='esewaverify'),

     path('register/',CustomerRegistration.as_view(),name='customerregistration'),
     path('logout/',CustomerLogoutView.as_view(),name='customerlogout'),
     path('login/',CustomerLoginView.as_view(),name='customerloginform'),
     
     path('profile/',CustomerDetailView.as_view(),name='customerprofile'),
     path('profile/order-<int:pk>/',CustomerOrderDetailView.as_view(),name='customerorderdetail'),
     path('search/',SearchView.as_view(),name="search"),
     #admin part
     path('admin-login/',AdminLoginView.as_view(),name='adminlogin'),
     path('admin-home/',AdminHomeView.as_view(),name='adminhome'),
     path('admin/order-<int:pk>/',AdminOrderDetailView.as_view(),name='adminorderdetail'),
     path('admin-all-order/',AdminOrderListView.as_view(),name='adminorder'),
     path('admin-order-<int:pk>-change/',AdminOrderStatusView.as_view(),name='adminorderstatus'),


]

ecomproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ecomapp.urls')),
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecomapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Admin(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    full_name=models.CharField(max_length=200)
    image=models.ImageField(upload_to='admins')
    mobile=models.CharField(max_length=20)

    def __str__(self):
        return self.user.username

class Customer(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address=models.CharField(max_length=200,blank=True,null=True)
    joined_on=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name

class Category(models.Model):
    title=models.CharField(max_length=200)
    slug=models.SlugField(unique=True)

    def __str__(self):
        return self.title

class Product(models.Model):
    title=models.CharField(max_length=200)
    slug=models.SlugField(unique=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products')
    marked_price =models.PositiveIntegerField()
    selling_price=models.PositiveIntegerField()
    description=models.TextField()
    warranty=models.CharField(max_length=300,null=True,blank=True)
    return_policy=models.CharField(max_length=300,null=True,blank=True)
    var_count=models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

class Cart(models.Model):
    customer=models.ForeignKey(Customer,on_delete=models.SET_NULL,null=True,blank=True)
    total=models.PositiveIntegerField(default=0)
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'cart' + str(self.id)

class CartProduct(models.Model):
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    rate=models.PositiveIntegerField()
    quantity=models.PositiveIntegerField()
    subtotal=models.PositiveIntegerField()

    def __str__(self):
        return 'cart' + str(self.cart.id) + 'cartproduct' + str(self.id)
ORDER_STATUS =(
    ('Order Received','Order Received'),
    ('Order Processing','Order Processing'),
    ('On the way','On the way'),
    ('Order Completed','Order Completed'),
    ('Order Canceled','Order Canceled'),
)
METHOD =(
    ("Cash On Delivery","Cash On Delivery"),
    ("Esewa",'Esewa'),
)

class Order(models.Model):
    cart=models.OneToOneField(Cart,on_delete=models.CASCADE)
    ordered_by=models.CharField(max_length=200)
    shipping_address=models.CharField(max_length=200)
    mobile=models.CharField(max_length=10)
    email=models.EmailField(null=True,blank=True)
    subtotal=models.PositiveIntegerField()
    discount=models.PositiveIntegerField()
    total=models.PositiveIntegerField()
    order_status=models.CharField(max_length=50,choices=ORDER_STATUS)
    created_at=models.DateTimeField(auto_now_add=True)
    payment_method=models.CharField(max_length=20,choices=METHOD,default="Cash On Delivery")
    payment_completed=models.BooleanField(default=False,null=True,blank=True)

    def __str__(self):
        return 'Order' + str(self.id)

templates/about.html
{% extends 'base.html'%}
{%block titile%}about{%endblock%}
{%block content%}
<h1>ABout page</h1>
{%endblock%}

templates/addtocart.html
{% extends 'base.html'%}
{%block title%}Add to cart{% endblock%}
{%block content%}
   <div class="container">
       <h3>Product added successfully</h3>
   </div>
{% endblock%}

templates/allproducts.html
{% extends 'base.html' %}
{%block title%}All Products{%endblock%}
{%block content%}
<div class="container">
    <h4>Categories wise Product list</h4>
    {%for cat in allproducts%}
    <h4><strong>{{cat.title}}</strong></h4>
    <hr>
     <div class="row">
        {%for p in cat.product_set.all%}
            <div class="col-md-4 card" style="border: 1px solid rgb(221, 220, 220);">
                <div class="m-3">
                <h5><a href="{% url 'ecomapp:productdetail' p.slug %}">{{p.title}}</a></h5>
                <img src="{{p.image.url}}" class="img-fluid" style="height:200px;object-fit:contain">
                <p class="mt-3">Price:R<strike>Rs.{{p.marked_price}}</strike> Rs.{{p.selling_price}}</p>
                <a href="{%url 'ecomapp:addtocart' p.id %}" class="btn btn-primary">Add to Cart</a>
                </div>
         </div>
        {%endfor%}
     </div>
    {%endfor%}
    <hr>
</div>
{%endblock%}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}{%endblock%}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'ecomapp:home'%}">Mountain Shop </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'ecomapp:home'%}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'ecomapp:allproducts'%}">Categories</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'ecomapp:mycart'%}">View Cart</a>
              </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                My Account
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {%if request.user.customer%}
                <a class="dropdown-item"  href="{% url 'ecomapp:customerlogout'%}">Logout</a>|
                <a class="dropdown-item"   href="{% url 'ecomapp:customerprofile'%}">My Profile</a>|
                {%else%}
                <a class="dropdown-item"   href="{% url 'ecomapp:customerregistration'%}">Registration</a> |
                <a  class="dropdown-item"  href="{% url 'ecomapp:customerloginform'%}">Login</a>
                {%endif%}
              </div>
            </li>
            {%if request.user.customer%}
            <li class="nav-item">
              <a class="nav-link" style="color: red;font-size:20px">Welcome {{request.user.username}}</a>
            </li>
            {%endif%}
          </ul>
          <form class="form-inline my-2 my-lg-0" action="/search/" method="GET" >
            <input name='keyword' class="form-control mr-sm-2" type="search" placeholder="Search product here" aria-label="Search" required>
            <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
    {% block content%}
    {%endblock%}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

templates/checkout.html
{% extends 'base.html'%}
{%block title%}Chekout{%endblock%}
{%block content%}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Item in the cart</h3>
            <a href="{% url 'ecomapp:mycart'%}">Update Cart</a>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>subtotal</th>
                    </tr>
                </thead>
                
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {%endfor%}
                    <tr>
                        <th colspan="4" class="text-right">Total:</th>
                        <th>Rs.{{cart.total}}</th>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
           <h3>Checkout Form</h3>
           <form action="" method="POST">
            {% csrf_token %} 
               {{form.as_p}}
               <button class="btn btn-success">Place Order</button>
           </form>
        </div>
    </div>
</div>
{%endblock%}

templates/contact.html
{% extends 'base.html'%}
{%block titile%}contact{%endblock%}
{%block content%}
<h1>Contact page</h1>
{%endblock%}

templates/customerloginform.html
{% extends 'base.html'%}
{%block titile%}Login{%endblock%}
{%block content%}
<style>
    .errorlist{
        color:red;
    }
</style>
<div class="container">
    <h3>Login Form</h3><hr>
    <div class="row">
        <div class="col-md-6 mx-auto">
            <form action="" method="POST">
                {%csrf_token%}
               {{form.as_p}}
               <button class="btn btn-primary">Login As a Customer</button>
               {%if error %}
               <li style="color:red">{{error}}</li>
               {%endif%}
            </form>
            <p>or don't have an account <a href="{% url 'ecomapp:customerregistration'%}{%if request.GET.next%}?next={{request.GET.next}}{%endif%}">Register here</a></p>
        </div>
    </div>
</div>
{%endblock%}

templates/customerprofile.html
{% extends 'base.html'%}
{%block titile%}Customer Profile{%endblock%}
{%block content%}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h3>Customer Profile</h3><hr>
            <p><span class="font-weight-bold">Full Name:</span> {{customer.full_name}}</p>
            <p><span class="font-weight-bold">Address:</span> {{customer.address}}</p>
            <p><span class="font-weight-bold">Email:</span> {{customer.user.email}}</p>
            <p><span class="font-weight-bold">UserName:</span> {{customer.user.username}}</p>
            <p><span class="font-weight-bold">Joined_on:</span> {{customer.joined_on}}</p>
        </div>
        <div class="col-md-8">
            <h3>Previous Order</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>OrderID</th>
                        <th>Amount</th>
                        <th>Order On</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {%for ord in orders%}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'ecomapp:customerorderdetail' ord.pk%}">#ORDER_{{ord.id}}</a></td>
                        <td>Rs.{{ord.total}}</td>
                        <td>{{ord.created_at|timesince}} ago</td>
                        <td>{{ord.order_status}}</td>
                    </tr>
                    {%endfor%}
                </tbody>
            </table>
        </div>
    </div>
</div>
{%endblock%}

templates/customerregistration.html
{% extends 'base.html'%}
{%block titile%}Registration{%endblock%}
{%block content%}
<style>
    .errorlist{
        color:red;
    }
</style>
<div class="container">
    <h3>Registration Form</h3><hr>
    <div class="row">
        <div class="col-md-6 mx-auto">
            <form action="" method="POST">
                {%csrf_token%}
               {{form.as_p}}
               <button class="btn btn-primary">Register As a Customer</button>
            </form>
            <p>Already have an account  <a href="{% url 'ecomapp:customerloginform'%}">Login here</a>
        </div>
    </div>
</div>
{%endblock%}

templates/esewarequest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        #myform{
            display:none;
        }
    </style>
</head>
<body>
    <h3 style="text-align: center;">You will be redirected to the Esewa Website..</h3>
    <form action="https://uat.esewa.com.np/epay/main" method="POST" id="myform">
        <input value="{{order.total}}" name="tAmt" type="hidden">
        <input value="{{order.total}}" name="amt" type="hidden">
        <input value="0" name="txAmt" type="hidden">
        <input value="0" name="psc" type="hidden">
        <input value="0" name="pdc" type="hidden">
        <input value="epay_payment" name="scd" type="hidden">
        <input value="order_{{order.id}}" name="pid" type="hidden">
        <input value="http://127.0.0.1:8000/esewa-verify/" type="hidden" name="su">
        <input value="{{request.build_absolute_uri}}" type="hidden" name="fu">
        <input value="Submit" type="submit">
    </form>
    <script>
        setTimeout(function(){
            document.getElementById("myform").submit()
        },500)
    </script>
</body>
</html>

templates/home.html
{% extends 'base.html'%}
{%block titile%}Home{%endblock%}
{%block content%}
<div class="container">
    <h3 class="text-center">Welcome to Mountain Shop</h3>
    <hr>
    <div class="row mt-4">
        {%for p in product_list%}
        <div class="col-md-4 card" style="border: 1px solid rgb(221, 220, 220);" >
                <div class="m-3">
            <h5><a href="{% url 'ecomapp:productdetail' p.slug %}">{{p.title}}</a></h5>
            <img src="{{p.image.url}}" class="img-fluid" style="height:200px;object-fit:contain">
           <p class="mt-3">Price<strike>Rs.{{p.marked_price}}</strike> Rs.{{p.selling_price}}</p>
           <a href="{%url 'ecomapp:addtocart' p.id %}" class="btn btn-primary">Add to Cart</a>
            </div>
        </div>
            {%endfor%}
    </div>
    <hr>
    <!-- boostrap pagination-->
    <nav aria-label="...">
        <ul class="pagination">
            {% if product_list.has_previous %}
          <li class="page-item ">
            <a class="page-link" href="?page={{ product_list.previous_page_number }}" tabindex="-1" aria-disabled="true">Previous</a>
          </li>
          {%else%}
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
          </li>
          {%endif%}
         
          {%for i in product_list.paginator.page_range%}
          {%if i == product_list.number%}
          <li class="page-item active"><a class="page-link" >{{i}}</a></li>
          {%else%}
          <li class="page-item"><a class="page-link" href="?page={{ i }}">{{i}}</a></li>
          {%endif%}
          {%endfor%}
          
          {% if product_list.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ product_list.next_page_number }}">Next</a>
          </li>
          {%else%}
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
          </li>
          {% endif %}
        </ul>
      </nav>
</div>
{%endblock%}

templates/mycart.html
{% extends 'base.html'%}
{%block titile%}My cart{%endblock%}
{%block content%}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h4>Item in my Cart</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>subtotal</th>
                        <th>Action</th>
                    </tr>
                </thead>
                
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                        <td>
                            <a href="{% url 'ecomapp:managecart' cp.id%}?action=inc" class="btn btn-primary">+</a>
                           {% if cp.quantity == 1%}
                            <a href="{% url 'ecomapp:managecart' cp.id%}?action=dcr"  class="btn btn-warning disabled" >-</a>
                            {%else %}
                            <a href="{% url 'ecomapp:managecart' cp.id%}?action=dcr"  class="btn btn-warning">-</a>
                            {%endif%}
                            <a href="{% url 'ecomapp:managecart' cp.id%}?action=rmv"  class="btn btn-danger">x</a>
                        </td>
                    </tr>
                    {%endfor%}
                    <tr>
                        <th colspan='4' class="text-right">Total</th>
                        <th>Rs.{{cart.total}}</th>
                        {%if cart.cartproduct_set.all%}
                        <th><a href="{% url 'ecomapp:emptycart'%}">Empty Cart</a>></th>
                        {%endif%}
                    </tr>
                    <tr>
                        <th><a href="{% url 'ecomapp:checkout'%}" class="btn btn-info">Checkout</a></th>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{%endblock%}

templates/productdetail.html
{% extends 'base.html'%}
{%block title%}{{product.title}}{%endblock%}
{%block content%}
<div class="container">
    <h4>Product:{{product.title}}</h4>
    <hr>
    <div class="row">
        <div class="col-md-6">
           <img alt="" src="{{product.image.url}}" class="img-fluid">
        </div>
        <div class="col-md-6">
            <h4>{{product.title}}</h4>
            <hr>
            <h5>Category:{{product.category}}(Viewed {{product.var_count}} times)</h5>
            <hr>
            <h5>Price:<br><strike>Rs.{{product.marked_price}}</strike> Rs.{{product.selling_price}}</h5>
            <hr>
            <a href="{% url 'ecomapp:addtocart' product.id %}" class="btn btn-info">Add to Cart</a>
            <hr>
            <h6>Warranty</h6>
            <p class="text-info">{{product.warranty}}</p>
            <h6>Return Policy</h6>
            <p class="text-info">{{product.return_policy}}</p>
            <hr>
            <h6>Description</h6>
            <p> {{product.description}}</p>
            <hr>
        </div>
    </div>
</div>

{%endblock%}

templates/search.html
{% extends 'base.html'%}
{%block titile%}Search{%endblock%}
{%block content%}
<div class="container">
   <div class="row">
       <div class="col-md-12">
           <h3>Search Results for <span class='text-info'>"{{request.GET.keyword}}"</span></h3>
           <hr>
           <div class="container">
            {% for result in results%}  
                <div class="row">
                   <div class="col-md-4">
                       <img src="{{result.image.url}}" class="img-fluid" alt="">
                   </div>
                   <div class="col-md-8">
                       <h4><a href="{% url 'ecomapp:productdetail' result.slug%}">{{result.title}}</a></h4>
                       <p>{{result.description|truncatewords:50}}</p>
                       <hr>
                       <h5>Price:<br><strike>Rs.{{result.marked_price}}</strike> Rs.{{result.selling_price}}</h5>
                       <hr>
                       <a href="{%url 'ecomapp:addtocart' result.id %}" class="btn btn-primary">Add to Cart</a>
                   </div>
                </div>   
            {%endfor%}
        </div>
       </div>
   </div>
</div>
{%endblock%}